export const mediaManifest = {
  'hero-system': {
    id: 'hero-system',
    kind: 'generated-art',
    src: './public/media/hero-vk-workflow-vertical.png',
    alt: 'Вертикальная иллюстрация VK-постинга от одного поста до множества сообщений и отчёта',
    label: 'Поток VK-постинга',
    description: 'Один исходный пост проходит через множество размещений и собирается в отчёт со скриншотами.',
    desktopAspect: '3 / 4',
    mobileAspect: '4 / 5',
    width: 1122,
    height: 1402,
    objectPosition: 'center',
    status: 'approved',
    promptRef: '04 Media Slots · hero-system',
  },
  supergroups: {
    id: 'supergroups',
    kind: 'generated-art',
    src: './public/media/supergroup-flow.png',
    alt: 'Иллюстрация супергруппы с несколькими сообществами и параметрами публикации',
    label: 'Сценарий супергруппы',
    description: 'Сгенерированный product-visual: общий пост, несколько сообществ и отдельные параметры размещения.',
    desktopAspect: '4 / 3',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · supergroups',
  },
  'post-variants': {
    id: 'post-variants',
    kind: 'real-screenshot',
    src: './scr/Корректировка под группы.png',
    alt: 'Разные версии одной публикации для нескольких сообществ',
    label: 'Варианты публикации',
    description: 'Один исходник адаптируется под разные площадки.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1210,
    status: 'approved',
    promptRef: '04 Media Slots · post-variants',
  },
  'report-builder': {
    id: 'report-builder',
    kind: 'real-screenshot',
    src: './scr/Сбор скриншотов.png',
    alt: 'Настройки автоматического отчёта в SMMБазе',
    label: 'Скриншот отчётности',
    description: 'Утверждённый скриншот настроек автоматического отчёта.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · report-builder',
  },
  'api-trust': {
    id: 'api-trust',
    kind: 'real-screenshot',
    src: './scr/Сотрудники.png',
    alt: 'Экран сотрудников SMMБазы с ролями и доступом к проектам',
    label: 'Роли и доступ команды',
    description: 'Реальный экран сотрудников: роли, проекты, отчёты и рабочие контакты команды.',
    desktopAspect: '3 / 2',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · api-trust',
  },
  'market-existing': {
    id: 'market-existing',
    kind: 'generated-art',
    src: './public/media/smmbaza-ecosystem.png',
    alt: 'Абстрактный визуал экосистемы SMMБазы с контентом, командами и медиатекой',
    label: 'Экосистема контента',
    description: 'Визуал направления, в котором Маркет соединяется с медиатекой и рабочими материалами команды.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · market-existing',
  },
  'ai-rewrites': {
    id: 'ai-rewrites',
    kind: 'generated-art',
    src: './public/media/ai-rewrites.png',
    alt: 'Один исходный пост и несколько вариантов текста',
    label: 'Будущий AI-сценарий',
    description: 'Будущая иллюстрация сценария рерайта одного исходника.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · ai-rewrites',
  },
  'og-cover': {
    id: 'og-cover',
    kind: 'brand-asset',
    src: './public/media/smmbaza-og-cover.png',
    alt: 'SMMБаза — автопостинг VK и отчёты со скриншотами',
    label: 'Social preview',
    description: 'Фирменная карточка для публикаций в социальных сетях.',
    desktopAspect: '1200 / 630',
    mobileAspect: '1200 / 630',
    width: 1727,
    height: 911,
    status: 'approved',
    promptRef: '04 Media Slots · og-cover',
  },
  'workflow-project': {
    id: 'workflow-project',
    kind: 'real-screenshot',
    src: './scr/Проекты.png',
    alt: 'Экран проектов и заказчиков SMMБазы',
    label: 'Рабочее пространство',
    description: 'Список заказчиков и проектов, с которого начинается настройка размещений.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · workflow-project',
  },
  'workflow-post': {
    id: 'workflow-post',
    kind: 'real-screenshot',
    src: './scr/Создать новый пост.png',
    alt: 'Экран создания нового поста в SMMБазе',
    label: 'Новый пост',
    description: 'Текст, медиафайлы, watermark и время публикации в одном сценарии.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · workflow-post',
  },
  'workflow-report': {
    id: 'workflow-report',
    kind: 'real-screenshot',
    src: './scr/Сбор скриншотов 6.png',
    alt: 'Готовый отчёт со скриншотами и метриками в SMMБазе',
    label: 'Готовый отчёт',
    description: 'Собранные публикации, скриншоты и показатели для передачи клиенту.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1118,
    status: 'approved',
    promptRef: '04 Media Slots · workflow-report',
  },
  'platform-projects': {
    id: 'platform-projects',
    kind: 'real-screenshot',
    src: './scr/Проекты.png',
    alt: 'Экран проектов и заказчиков SMMБазы',
    label: 'Проекты и заказчики',
    description: 'Обзор рабочего пространства с заказчиками и проектами.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-projects',
  },
  'platform-project': {
    id: 'platform-project',
    kind: 'real-screenshot',
    src: './scr/Проект.png',
    alt: 'Детальная страница проекта SMMБазы',
    label: 'Карточка проекта',
    description: 'Проект, группы, проверяющие, комментарии и отчёты в одном экране.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1738,
    status: 'approved',
    promptRef: '04 Media Slots · platform-project',
  },
  'platform-supergroups': {
    id: 'platform-supergroups',
    kind: 'real-screenshot',
    src: './scr/Супергруппы.png',
    alt: 'Список супергрупп в SMMБазе',
    label: 'Супергруппы',
    description: 'Несколько сообществ объединены в управляемые наборы.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-supergroups',
  },
  'platform-new-post': {
    id: 'platform-new-post',
    kind: 'real-screenshot',
    src: './scr/Создать новый пост.png',
    alt: 'Экран создания нового поста в SMMБазе',
    label: 'Создать пост',
    description: 'Текст, медиафайлы и расписание публикации.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-new-post',
  },
  'platform-post-registry': {
    id: 'platform-post-registry',
    kind: 'real-screenshot',
    src: './scr/Реестр постов.png',
    alt: 'Реестр публикаций SMMБазы',
    label: 'Реестр постов',
    description: 'Публикации, скриншоты, сотрудники и ссылки в одной таблице.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-post-registry',
  },
  'platform-report': {
    id: 'platform-report',
    kind: 'real-screenshot',
    src: './scr/Сбор скриншотов 6.png',
    alt: 'Отчёт со скриншотами и метриками в SMMБазе',
    label: 'Собранный отчёт',
    description: 'Показатели и публикации подготовлены для проверки и передачи клиенту.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1118,
    status: 'approved',
    promptRef: '04 Media Slots · platform-report',
  },
};
