export const mediaManifest = {
  'hero-system': {
    id: 'hero-system',
    kind: 'generated-art',
    src: './public/media/optimized/hero-system.webp',
    srcSet: './public/media/optimized/hero-system-480.webp 480w, ./public/media/optimized/hero-system-960.webp 960w, ./public/media/optimized/hero-system.webp 1122w',
    alt: 'Вертикальная иллюстрация VK-постинга от одного поста до множества сообщений и отчёта',
    label: 'Поток VK-постинга',
    description: 'Один исходный пост проходит через множество размещений и собирается в отчёт со скриншотами.',
    desktopAspect: '3 / 4',
    mobileAspect: '4 / 5',
    width: 1122,
    height: 1402,
    objectPosition: 'center',
    status: 'approved',
    promptRef: '04 Media Slots · hero-system',
  },
  supergroups: {
    id: 'supergroups',
    kind: 'generated-art',
    src: './public/media/optimized/supergroups-art.webp',
    srcSet: './public/media/optimized/supergroups-art-480.webp 480w, ./public/media/optimized/supergroups-art-960.webp 960w, ./public/media/optimized/supergroups-art.webp 1586w',
    alt: 'Иллюстрация супергруппы с несколькими сообществами и параметрами публикации',
    label: 'Сценарий супергруппы',
    description: 'Сгенерированный product-visual: общий пост, несколько сообществ и отдельные параметры размещения.',
    desktopAspect: '4 / 3',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · supergroups',
  },
  'group-registry': {
    id: 'group-registry',
    kind: 'generated-art',
    src: './public/media/optimized/group-registry.webp',
    srcSet: './public/media/optimized/group-registry-480.webp 480w, ./public/media/optimized/group-registry-960.webp 960w, ./public/media/optimized/group-registry.webp 1586w',
    alt: 'Демонстрационный визуал реестра групп, тегов и иерархии доступа команды',
    label: 'Реестр групп и роли',
    description: 'Демонстрационный визуал структуры реестра и трёх уровней доступа.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · group-registry',
  },
  'autorepost-flow': {
    id: 'autorepost-flow',
    kind: 'generated-art',
    src: './public/media/optimized/autorepost-flow.webp',
    srcSet: './public/media/optimized/autorepost-flow-480.webp 480w, ./public/media/optimized/autorepost-flow-960.webp 960w, ./public/media/optimized/autorepost-flow.webp 1586w',
    alt: 'Демонстрационный визуал авторепоста из одного поста в несколько групп по тегам',
    label: 'Сценарий авторепоста',
    description: 'Демонстрационный визуал: ссылка на исходный пост, теги групп и несколько размещений.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · autorepost-flow',
  },
  'post-variants': {
    id: 'post-variants',
    kind: 'real-screenshot',
    src: './scr/optimized/post-variants.webp',
    srcSet: './scr/optimized/post-variants-480.webp 480w, ./scr/optimized/post-variants-960.webp 960w, ./scr/optimized/post-variants.webp 1236w',
    alt: 'Разные версии одной публикации для нескольких сообществ',
    label: 'Варианты публикации',
    description: 'Один исходник адаптируется под разные площадки.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1210,
    status: 'approved',
    promptRef: '04 Media Slots · post-variants',
  },
  'report-builder': {
    id: 'report-builder',
    kind: 'real-screenshot',
    src: './scr/optimized/report-builder.webp',
    srcSet: './scr/optimized/report-builder-480.webp 480w, ./scr/optimized/report-builder-960.webp 960w, ./scr/optimized/report-builder.webp 1236w',
    alt: 'Настройки автоматического отчёта в SMMБазе',
    label: 'Скриншот отчётности',
    description: 'Утверждённый скриншот настроек автоматического отчёта.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · report-builder',
  },
  'api-trust': {
    id: 'api-trust',
    kind: 'real-screenshot',
    src: './scr/optimized/api-trust.webp',
    srcSet: './scr/optimized/api-trust-480.webp 480w, ./scr/optimized/api-trust-960.webp 960w, ./scr/optimized/api-trust.webp 1236w',
    alt: 'Экран сотрудников SMMБазы с ролями и доступом к проектам',
    label: 'Роли и доступ команды',
    description: 'Реальный экран сотрудников: роли, проекты, отчёты и рабочие контакты команды.',
    desktopAspect: '3 / 2',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · api-trust',
  },
  'market-existing': {
    id: 'market-existing',
    kind: 'generated-art',
    src: './public/media/optimized/market-existing.webp',
    srcSet: './public/media/optimized/market-existing-480.webp 480w, ./public/media/optimized/market-existing-960.webp 960w, ./public/media/optimized/market-existing.webp 1586w',
    alt: 'Абстрактный визуал экосистемы SMMБазы с контентом, командами и медиатекой',
    label: 'Экосистема контента',
    description: 'Демонстрационный визуал существующего раздела; точное назначение Маркета уточняется.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · market-existing',
  },
  'ai-rewrites': {
    id: 'ai-rewrites',
    kind: 'generated-art',
    src: './public/media/optimized/ai-rewrites.webp',
    srcSet: './public/media/optimized/ai-rewrites-480.webp 480w, ./public/media/optimized/ai-rewrites-960.webp 960w, ./public/media/optimized/ai-rewrites.webp 1586w',
    alt: 'Один исходный пост и несколько вариантов текста',
    label: 'Будущий AI-сценарий',
    description: 'Будущая иллюстрация сценария рерайта одного исходника.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1586,
    height: 992,
    status: 'approved',
    promptRef: '04 Media Slots · ai-rewrites',
  },
  'og-cover': {
    id: 'og-cover',
    kind: 'brand-asset',
    src: './public/media/optimized/smmbaza-og-cover.jpg',
    alt: 'SMMБаза — автопостинг VK и отчёты со скриншотами',
    label: 'Social preview',
    description: 'Фирменная карточка для публикаций в социальных сетях.',
    desktopAspect: '1200 / 630',
    mobileAspect: '1200 / 630',
    width: 1200,
    height: 630,
    status: 'approved',
    promptRef: '04 Media Slots · og-cover',
  },
  'workflow-project': {
    id: 'workflow-project',
    kind: 'real-screenshot',
    src: './scr/optimized/projects.webp',
    srcSet: './scr/optimized/projects-480.webp 480w, ./scr/optimized/projects-960.webp 960w, ./scr/optimized/projects.webp 1236w',
    alt: 'Экран проектов и заказчиков SMMБазы',
    label: 'Рабочее пространство',
    description: 'Список заказчиков и проектов, с которого начинается настройка размещений.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · workflow-project',
  },
  'workflow-post': {
    id: 'workflow-post',
    kind: 'real-screenshot',
    src: './scr/optimized/new-post.webp',
    srcSet: './scr/optimized/new-post-480.webp 480w, ./scr/optimized/new-post-960.webp 960w, ./scr/optimized/new-post.webp 1236w',
    alt: 'Экран создания нового поста в SMMБазе',
    label: 'Новый пост',
    description: 'Текст, медиафайлы, водяной знак и время публикации в одном сценарии.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · workflow-post',
  },
  'workflow-report': {
    id: 'workflow-report',
    kind: 'real-screenshot',
    src: './scr/optimized/report-final.webp',
    srcSet: './scr/optimized/report-final-480.webp 480w, ./scr/optimized/report-final-960.webp 960w, ./scr/optimized/report-final.webp 1236w',
    alt: 'Готовый отчёт со скриншотами и метриками в SMMБазе',
    label: 'Готовый отчёт',
    description: 'Собранные публикации, скриншоты и показатели для передачи клиенту.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1118,
    status: 'approved',
    promptRef: '04 Media Slots · workflow-report',
  },
  'platform-projects': {
    id: 'platform-projects',
    kind: 'real-screenshot',
    src: './scr/optimized/projects.webp',
    srcSet: './scr/optimized/projects-480.webp 480w, ./scr/optimized/projects-960.webp 960w, ./scr/optimized/projects.webp 1236w',
    alt: 'Экран проектов и заказчиков SMMБазы',
    label: 'Проекты и заказчики',
    description: 'Обзор рабочего пространства с заказчиками и проектами.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-projects',
  },
  'platform-project': {
    id: 'platform-project',
    kind: 'real-screenshot',
    src: './scr/optimized/project-detail.webp',
    srcSet: './scr/optimized/project-detail-480.webp 480w, ./scr/optimized/project-detail-960.webp 960w, ./scr/optimized/project-detail.webp 1236w',
    alt: 'Детальная страница проекта SMMБазы',
    label: 'Карточка проекта',
    description: 'Проект, группы, проверяющие, комментарии и отчёты в одном экране.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1738,
    status: 'approved',
    promptRef: '04 Media Slots · platform-project',
  },
  'platform-supergroups': {
    id: 'platform-supergroups',
    kind: 'real-screenshot',
    src: './scr/optimized/supergroups-screen.webp',
    srcSet: './scr/optimized/supergroups-screen-480.webp 480w, ./scr/optimized/supergroups-screen-960.webp 960w, ./scr/optimized/supergroups-screen.webp 1236w',
    alt: 'Список супергрупп в SMMБазе',
    label: 'Супергруппы',
    description: 'Несколько сообществ объединены в управляемые наборы.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-supergroups',
  },
  'platform-new-post': {
    id: 'platform-new-post',
    kind: 'real-screenshot',
    src: './scr/optimized/new-post.webp',
    srcSet: './scr/optimized/new-post-480.webp 480w, ./scr/optimized/new-post-960.webp 960w, ./scr/optimized/new-post.webp 1236w',
    alt: 'Экран создания нового поста в SMMБазе',
    label: 'Создать пост',
    description: 'Текст, медиафайлы и расписание публикации.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-new-post',
  },
  'platform-post-registry': {
    id: 'platform-post-registry',
    kind: 'real-screenshot',
    src: './scr/optimized/post-registry.webp',
    srcSet: './scr/optimized/post-registry-480.webp 480w, ./scr/optimized/post-registry-960.webp 960w, ./scr/optimized/post-registry.webp 1236w',
    alt: 'Реестр публикаций SMMБазы',
    label: 'Реестр постов',
    description: 'Публикации, скриншоты, сотрудники и ссылки в одной таблице.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 768,
    status: 'approved',
    promptRef: '04 Media Slots · platform-post-registry',
  },
  'platform-report': {
    id: 'platform-report',
    kind: 'real-screenshot',
    src: './scr/optimized/report-final.webp',
    srcSet: './scr/optimized/report-final-480.webp 480w, ./scr/optimized/report-final-960.webp 960w, ./scr/optimized/report-final.webp 1236w',
    alt: 'Отчёт со скриншотами и метриками в SMMБазе',
    label: 'Собранный отчёт',
    description: 'Показатели и публикации подготовлены для проверки и передачи клиенту.',
    desktopAspect: '16 / 10',
    mobileAspect: '4 / 3',
    width: 1236,
    height: 1118,
    status: 'approved',
    promptRef: '04 Media Slots · platform-report',
  },
};
